name = "ferienwoche"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
node_compat = true
account_id = "9a0d3ae785f5f07eb410e63ec29712ec"

[site]
bucket = ".output/public"
