name: Deployment CI
on:
  push:
  pull_request:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm run build
        if: github.ref_name == 'main'
        env:
          NITRO_PRESET: cloudflare
      - name: Deploy
        if: github.ref_name == 'main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}